language: go
sudo: false
cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin
    - $GOPATH/src/github.com/golang
    - $GOPATH/src/github.com/golangci
install:
  - if [[ $DEP_TOOL == "dep" ]]; then go get github.com/golangci/golangci-lint github.com/golang/dep/cmd/dep; fi
  - if [[ $DEP_TOOL == "dep" ]]; then dep ensure -v; fi
  - if [[ $DEP_TOOL == "mod" ]]; then go get github.com/golangci/golangci-lint@latest; fi
  - if [[ $DEP_TOOL == "mod" ]]; then go mod download; fi
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals -D unparam --deadline 5m ./...
  - go test -race ./...
env:
  matrix:
    - DEP_TOOL=dep GO111MODULE=off
    - DEP_TOOL=mod GO111MODULE=on
go:
  - 1.10.x
  - 1.11.x
  - 1.12rc1
  - tip
matrix:
  fast_finish: true
  exclude:
    - go: 1.10.x
      env: DEP_TOOL=mod GO111MODULE=on
    - go: 1.10.x
      env: DEP_TOOL=mod GO111MODULE=on
